import type { IconName } from '../components/Icon'

const EXTENSION_TO_ICON: Record<string, IconName> = {
  md: 'markdown',
  markdown: 'markdown',
  csv: 'table',
  tsv: 'table',
  pdf: 'file-pdf',
  json: 'json',
  jsonc: 'json',
  ipynb: 'notebook',
  png: 'file-media',
  jpg: 'file-media',
  jpeg: 'file-media',
  gif: 'file-media',
  webp: 'file-media',
  bmp: 'file-media',
  svg: 'file-media',
  ico: 'file-media',
  avif: 'file-media',
  tiff: 'file-media',
  zip: 'file-zip',
  tar: 'file-zip',
  gz: 'file-zip',
  '7z': 'file-zip',
  rar: 'file-zip',
  txt: 'file-text',
  log: 'file-text',
  ts: 'file-code',
  tsx: 'file-code',
  js: 'file-code',
  jsx: 'file-code',
  mjs: 'file-code',
  cjs: 'file-code',
  py: 'file-code',
  go: 'file-code',
  rs: 'file-code',
  rb: 'file-code',
  java: 'file-code',
  c: 'file-code',
  cpp: 'file-code',
  h: 'file-code',
  hpp: 'file-code',
  cs: 'file-code',
  kt: 'file-code',
  swift: 'file-code',
  php: 'file-code',
  lua: 'file-code',
  r: 'file-code',
  scala: 'file-code',
  sh: 'file-code',
  zsh: 'file-code',
  bash: 'file-code',
  fish: 'file-code',
  ps1: 'file-code',
  css: 'file-code',
  scss: 'file-code',
  sass: 'file-code',
  less: 'file-code',
  html: 'file-code',
  htm: 'file-code',
  xml: 'file-code',
  yml: 'file-code',
  yaml: 'file-code',
  toml: 'file-code',
  ini: 'file-code',
  sql: 'file-code',
}

export function fileIconFor(name: string): IconName {
  const idx = name.lastIndexOf('.')
  if (idx <= 0) return 'file'
  const ext = name.slice(idx + 1).toLowerCase()
  return EXTENSION_TO_ICON[ext] ?? 'file'
}
