// Generates src/components/Icon.tsx from src/icons/*.svg. Re-run after
// refreshing src/icons/ from upstream microsoft/vscode-codicons.
const fs = require('node:fs')
const path = require('node:path')

const ICONS_DIR = path.join(__dirname, '..', 'src', 'icons')
const OUT = path.join(__dirname, '..', 'src', 'components', 'Icon.tsx')

const files = fs
  .readdirSync(ICONS_DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort()

const entries = files.map((file) => {
  const name = file.replace(/\.svg$/, '')
  const raw = fs.readFileSync(path.join(ICONS_DIR, file), 'utf8')
  // Some SVGs are self-closing (e.g. blank.svg) — no inner content.
  if (/<svg[^>]*\/>/.test(raw)) return [name, '']
  const m = raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)
  if (!m) throw new Error(`No <svg> wrapper in ${file}`)
  const inner = m[1].replace(/\s+/g, ' ').trim()
  return [name, inner]
})

const body = entries
  .map(([name, inner]) => `  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`)
  .join('\n')

const out = `// AUTO-GENERATED by scripts/build-icons.cjs — do not edit by hand.
// Source: microsoft/vscode-codicons (MIT). See src/icons/LICENSE and NOTICE.md.

const ICONS = {
${body}
} as const

export type IconName = keyof typeof ICONS

type Props = {
  name: IconName
  size?: number
  className?: string
}

export function Icon({ name, size = 16, className }: Props) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 16 16"
      fill="currentColor"
      aria-hidden="true"
      className={className}
      dangerouslySetInnerHTML={{ __html: ICONS[name] }}
    />
  )
}
`

fs.writeFileSync(OUT, out)
console.log(`Wrote ${OUT} with ${entries.length} icons`)
